language: java
install: mvn install -DskipTests
jdk:
  - oraclejdk8
addons:
  firefox: "44.0"
env:
  - DISPLAY=:99
script:
  - mvn clean integration-test
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
after_failure:
  - find . -name "TestSuite.txt" | xargs cat
